# default: &default
#   client_id: '971181149334-d9avbf8shp6ku8vgpvlkbntcohonhh5s.apps.googleusercontent.com'
#   client_secret: '5UgDl6FSacW1DYobM11yPhJt'

development:
  client_id: '890464551227-vlrtvoqgamv76vtaqn9hm05bl304ldvu.apps.googleusercontent.com'
  client_secret: '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'

test:
  client_id: '890464551227-vlrtvoqgamv76vtaqn9hm05bl304ldvu.apps.googleusercontent.com'
  client_secret: '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'

production:
  client_id: '890464551227-vlrtvoqgamv76vtaqn9hm05bl304ldvu.apps.googleusercontent.com'
  client_secret: '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'
  
